project_id = "waehzhneropydndrxxdi"

[functions.create-google-meet]
verify_jwt = true

[functions.get-google-client-id]
verify_jwt = false

[functions.get-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
